### ISSUE TITLE
Preserve <br/>s in cells

### ISSUE THREAD

**Issue by hughrawlinson** [atye/wikitable2json#105]
Hi! I'm hoping to use this API to grab a table which contains multiple semantic elements in one cell - as shown [in this example](https://en.wikipedia.org/wiki/Candidates_in_the_2024_Irish_general_election). Each element in the cell is separated with a <br/> tag, but in the API output that tag is stripped, so I have no way of identifying the delineations between each element.

Additionally, some of the elements are links, it would be great to preserve the link target too. I see that the verbose option includes links, but since the text is still grouped and stripped of <br>s it's impossible to match each link to each element.

Thanks!

**Comment by atye** [comment]
Hello. I'll see what can be done about preserving <br> elements.

**Comment by atye** [comment]
This is a limitation in https://github.com/PuerkitoBio/goquery. I've opened https://github.com/PuerkitoBio/goquery/issues/497 to get the maintainer's thoughts about new functionality to handle this.

If it gets rejected, I'll consider forking that repository and implementing it.

**Comment by atye** [comment]
Could you give an example of the result you're looking for? Would you prefer `"Leonora Carey\nJoe Cooney\nTom Nolan[7]"` or `"Leonora Carey<br>Joe Cooney<br>Tom Nolan[7]"`? Or something else?

**Comment by hughrawlinson** [comment]
I think either of those two would work fine for my purposes. Thanks!

**Comment by hughrawlinson** [comment]
I guess one thing to consider too is that if the goal were to match links to their parts of the text, preserving the <br>s (or \ns) wouldn't be enough - there are multiple links in one line. Maybe the `links` object could have an option to return a list of objects with the href and the text of that link, rather than just the link? I think that should make it possible to pick out the data. I suspect there are more cases though - I wonder if more than just text can be inside a link for example.

**Comment by hughrawlinson** [comment]
Yeah that looks perfect!

**Comment by atye** [comment]
To enable `br` elements as a new line, there will be a new query parameter `brNewLine`.

`?verbose=true&brNewLine=true`

Using the the above parameters on the page you provided, have a look at the result [here](https://pastebin.com/mWS7nn3R) and let me know how that looks. I think it's good.

If you'd like to use the changes, you can checkout branch `issue-105` and execute `make run` to run the docker container.

**Comment by hughrawlinson** [comment]
Looks great to me!

**Comment by atye** [comment]
The changes are live. If you have further feature requests, let's open a new issue.

I hope this has been helpful for your projects!

**Comment by atye** [comment]
Actually, I'll leave this open for a day or two incase there are some issues with it.

**Comment by hughrawlinson** [comment]
Thanks! This is great. I really appreciate it!
