### ISSUE TITLE
Use `theader` and `th` elements for keyValue format

### ISSUE THREAD

**Issue by atye** [atye/wikitable2json#52]
Current keyValue approach doesn't account for nested columns. `theader` and `th` elements should be used.

**Comment by atye** [comment]
@LukePrior

Try this.

https://www.wikitable2json.com/api/Opinion_polling_for_the_2022_Australian_federal_election?table=0&keyRows=2

`keyRows` lets you specify the number of rows, starting from the first row, to use as keys. For this table, the first two rows are keys.

**Comment by LukePrior** [comment]
You are amazing!

That works perfectly.

Thanks.

**Comment by LukePrior** [comment]
Sorry, I'm just checking the data and not all the columns line up correctly:

![image](https://user-images.githubusercontent.com/22492406/165434090-72395d64-36ff-4023-b3ea-f79ac433947a.png)

```
{"2pp vote ALP":"53%","2pp vote L/NP":"47%","Brand":"Newspoll-YouGov","Date":"20–23 April 2022","Interview mode":"Online","Primary vote ALP":"11%","Primary vote GRN":"3%","Primary vote L/NP":"36%","Primary vote ONP":"4%","Primary vote UAP":"9%","Primary vote UND":"37%","Sample size":"1538","UND OTH":"–"}
```

So the 2pp is correct but the primary vote isn't aligned correctly.

Is this a problem with the table or the code?

**Comment by LukePrior** [comment]
I also noticed another small quality of life improvement, I think you should remove any trailing whitespace from the keys and entries. I ran into some problems as on another table the key was `"Date "` and not `"Date"`.

**Comment by atye** [comment]
@LukePrior 

There were some issues with the code. These should be correct now. Let me know.

https://www.wikitable2json.com/api/Opinion_polling_for_the_2022_Australian_federal_election?table=0&cleanRef=true
https://www.wikitable2json.com/api/Opinion_polling_for_the_2022_Australian_federal_election?table=0&cleanRef=true&keyRows=2

The code trims leading and trailing whitespace from the text so it should be trimmed. If something isn't trimmed, you can open a new issue with the details.

**Comment by LukePrior** [comment]
LGTM
