### ISSUE TITLE
cleanRef doesn't remove [citation needed]

### ISSUE THREAD

**Issue by LukePrior** [atye/wikitable2json#56]
I'm not sure if you think this should be added but the API doesn't currently remove [citation needed] tags when cleanRef is enabled.

![image](https://user-images.githubusercontent.com/22492406/172632810-1193d3dc-8ab9-446b-b002-8fc96fd5377e.png)

https://www.wikitable2json.com/api/Phase-out_of_fossil_fuel_vehicles?lang=en&cleanRef=true&keyRows=1&table=0

```
{
     "Country":"Macau",
     "Details":"New private vehicle sales and registration.",
     "Scope":"Diesel, petrol",
     "Start year":"2035[citation needed]",
     "Status":"Macau Legislature plan, Special Administrative Region of the People's Republic Of China."
}
```

Here is the dev tools of the HTML element:

![image](https://user-images.githubusercontent.com/22492406/172633094-9b2eff04-dbc2-4d1c-bc96-c39f36f55728.png)

**Comment by atye** [comment]
I think this can be included in the `cleanRef` functionality. I'll see what can be done.

**Comment by atye** [comment]
@LukePrior 

Should be updated. Let me know if it works for you.

**Comment by LukePrior** [comment]
Look's good thanks.
