### ISSUE TITLE
Parsing issue with ñ in URL

### ISSUE THREAD

**Issue by anthony-fp** [atye/wikitable2json#68]
https://www.wikitable2json.com/api/2022_Vuelta_a_España does not load data correctly

**Comment by atye** [comment]
Hi @anthony-fp. The ñ is fine. The error is:

```
{"error":"no integer value in span attribute: [5;]","code":500,"details":{"ColumnNumber":3,"RowNumber":11,"TableIndex":0}}
```

In the first table at row index 11 and column index 3, there is a `colspan` attribute with the value of `5;` which my API tries to parse as an integer, but fails because of the `;`.

```
<td style="text-align:center" colspan="5;">Rest day</td>
```

You'll have to edit the table to remove the `;` from the colspan.

**Comment by anthony-fp** [comment]
thanks!

**Comment by atye** [comment]
I see the page is working now so I'll close this. Feel free to open another issue if something else comes up.
