### ISSUE TITLE
Add optional the all informations from the table including e.g. the actual link

### ISSUE THREAD

**Issue by zukunft** [atye/wikitable2json#93]
It would be nice, if there is an option to include all information from the table in the json e.g. for ISO_3166-1 it returns "Bolivia, Plurinational State of" but the link which is only "Bolivia".

If I call https://www.wikitable2json.com/api/ISO_3166-1 I get:

...
,["Bolivia, Plurinational State of","BO","BOL","068","ISO 3166-2:BO","Yes"],
...

Would be nice if there would be an option to receive e.g. :

...
,[["Bolivia, Plurinational State of","Bolivia"],"BO","BOL","068","ISO 3166-2:BO","Yes"],
...

or 

...
,["Bolivia, Plurinational State of",{"link": "Bolivia"}],,"BO","BOL","068","ISO 3166-2:BO","Yes"],
...

**Comment by atye** [comment]
I'm away from my computer but I'll look into this next week.

**Comment by atye** [comment]
Having the link value as a separate value in the response like `["Bolivia, Plurinational State of","Bolivia"]` or `["Bolivia, Plurinational State of",{"link": "Bolivia"}]` may be tricky because each value represents a different row or column. But in this case, the link value is a part of the row or column value.

What do you think about an option to enable a response like this? Each value contains the text and the link value. This maintains the structure of keeping each row or column as its own value and it's easy to add fields in the future.

```
[
  {
    "text": "Bolivia, Plurinational State of",
    "link": "Boliva"
  },
  {
    "text": "BO",
    "link": ""
  }
]
```

**Comment by atye** [comment]
It's been three weeks. You can re-open this if you still want to discuss.

**Comment by zukunft** [comment]
Sorry, this time I have been away from my PC. Your suggestion looks fine for me.

**Comment by atye** [comment]
I decided to make the links an array because a cell could have multiple links in the text.

Here is the matrix format:
```
 [
      {
        "text": "Bolivia, Plurinational State of",
        "links": [
          "Bolivia"
        ]
      },
      {
        "text": "BO",
        "links": [
          "ISO_3166-1_alpha-2#BO"
        ]
      },
      {
        "text": "BOL",
        "links": null
      },
      {
        "text": "068",
        "links": null
      },
      {
        "text": "ISO 3166-2:BO",
        "links": [
          "ISO_3166-2:BO"
        ]
      },
      {
        "text": "Yes",
        "links": null
      }
    ]
```

keyValue format:
```
    {
      "Alpha-2 code": {
        "text": "BO",
        "links": [
          "ISO_3166-1_alpha-2#BO"
        ]
      },
      "Alpha-3 code": {
        "text": "BOL",
        "links": null
      },
      "English short name  (using title case)": {
        "text": "Bolivia, Plurinational State of",
        "links": [
          "Bolivia"
        ]
      },
      "Independent": {
        "text": "Yes",
        "links": null
      },
      "Link to  ISO 3166-2": {
        "text": "ISO 3166-2:BO",
        "links": [
          "ISO_3166-2:BO"
        ]
      },
      "Numeric code": {
        "text": "068",
        "links": null
      }
    }
```
